name: CI
on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/ci.yml"
      - "Package.swift"
      - "**/*.swift"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "Package.swift"
      - "**/*.swift"
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict

  build:
    runs-on: macos-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      # Issues with other Xcode versions, so we need to specify the version explicitly
      - run: sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer
      - name: Build
        run: |
          xcodebuild -project Thaw.xcodeproj \
          -scheme Thaw \
          -destination platform=macOS \
          -configuration Release \
          MACOSX_DEPLOYMENT_TARGET=14.0 \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          build
